[project]
name = "air-traffic-allocation-genetic-algorithm"
version = "0.1.0"
description = ""
authors = [
    {name = "Eduardo Cabrera",email = "eduardo.cabrera@gscap.com.br"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deap (>=1.4.3,<2.0.0)",
    "pandas (>=2.3.3,<3.0.0)",
    "matplotlib (>=3.10.7,<4.0.0)",
    "tqdm (>=4.66.0,<5.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
